### ISSUE TITLE
uproot.dask(<some tree specifier>) does not know about behaviors?

### ISSUE THREAD

**Issue by lgray** [dask-contrib/dask-awkward#100]
Hi!

When I try the following using: awkward 2.0.0rc3, uproot 5.0.0.rc6, dask-awkward 2022.11a0, I get a handle that appears to be an dask-awkward record array which should have a behavior:
```bash
$ wget https://github.com/CoffeaTeam/coffea/blob/master/tests/samples/nano_dy.root?raw=true
$ python
```
```python3
>>> import uproot
>>> tree = uproot.dask({"./nano_dy.root": "Events"})
>>> tree.behavior
```
but it results in:
```
>>> tree.behavior
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 927, in __getattr__
    return self._call_behavior_property(attr)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 894, in _call_behavior_property
    return self.map_partitions(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 967, in map_partitions
    return map_partitions(func, self, *args, **kwargs)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 1295, in map_partitions
    return new_array_object(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 1114, in new_array_object
    actual_meta = compute_typetracer(dsk, name)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 1061, in compute_typetracer
    return typetracer_array(Delayed(key, dsk.cull({key}), layer=name).compute())
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 1573, in typetracer_array
    raise TypeError(msg)
TypeError: `a` should be an awkward array or a Dask awkward collection.
Got type <class 'NoneType'>
```

Is this expected? In either case how do I add to or alter the behavior of a dask array?

**Comment by douglasdavis** [comment]
I think @agoose77 is right, to mirror the `awkward` API we'll need to add a property to the dask-awkward `Array` that reports the behavior via its `_meta`.

**Comment by douglasdavis** [comment]
> how do I add to or alter the behavior of a dask array?

**Comment by lgray** [comment]
Cool, we heavily use behaviors in coffea for a number for pieces of functionality. It would be useful to chat, in general, about how our NanoEvents representation layer operates using dask-awkward.

**Comment by douglasdavis** [comment]
Just uploaded dask-awkward 2022.11a1 to PyPI, which includes a commit that added a `behavior` property to the `Array` collection.

**Comment by lgray** [comment]
Awesome - thank you. I will keep this issue alive as I work through getting a few things going with NanoEvents and dask-awkward, if that's fine with you.

There are some major architectural choices we should discuss once the baseline (i.e. current user interface) is recovered.

**Comment by lgray** [comment]
@nsmith- FYI

**Comment by lgray** [comment]
@douglasdavis @agoose77  We will also need awkward.with_name support for dask arrays, corresponding to behaviors. Right now using `ak.with_name` results in:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lgray/coffea-dev/coffea/coffea/nanoevents/schemas/base.py", line 115, in apply_to_dask
    dask_record = awkward.with_name(dask_record, "NanoEvents")
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_with_name.py", line 35, in with_name
    return _impl(array, name, highlevel, behavior)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_with_name.py", line 40, in _impl
    layout = ak.operations.to_layout(array)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_to_layout.py", line 45, in to_layout
    return _impl(array, allow_record, allow_other, numpytype)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_to_layout.py", line 134, in _impl
    ak.operations.from_iter(array, highlevel=False),
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_from_iter.py", line 64, in from_iter
    return _impl(iterable, highlevel, behavior, allow_record, initial, resize)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_from_iter.py", line 89, in _impl
    builder.fromiter(iterable)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 930, in wrapper
    return self._call_behavior_method(attr, *args, **kwargs)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 891, in _call_behavior_method
    return self.map_partitions(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 975, in map_partitions
    return map_partitions(func, self, *args, **kwargs)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 1303, in map_partitions
    return new_array_object(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 1122, in new_array_object
    actual_meta = compute_typetracer(dsk, name)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 1069, in compute_typetracer
    return typetracer_array(Delayed(key, dsk.cull({key}), layer=name).compute())
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 1581, in typetracer_array
    raise TypeError(msg)
TypeError: `a` should be an awkward array or a Dask awkward collection.
Got type <class 'list'>
```

Would it be possible to fix this in another pre-release?

**Comment by lgray** [comment]
I get the same error when using `ak.with_parameter`, we use parameters quite a lot to annotate arrays with TTree metadata.

**Comment by lgray** [comment]
Ah - OK I wasn't sure how y'all were passing things through or otherwise supplementing the functionality. Thanks!

**Comment by lgray** [comment]
```
>>> BaseSchema.apply_to_dask(x)
/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py:1276: UserWarning: metadata could not be determined; a compute on the first partition will occur.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lgray/coffea-dev/coffea/coffea/nanoevents/schemas/base.py", line 116, in apply_to_dask
    dask_record = dask_awkward.with_parameter(dask_record, "metadata", {})
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/structure.py", line 481, in with_parameter
    raise DaskAwkwardNotImplemented("TODO")
dask_awkward.utils.DaskAwkwardNotImplemented: TODO

If you would like this unsupported call to be supported by
dask-awkward please open an issue at:
https://github.com/ContinuumIO/dask-awkward.
```
Well - different error but same outcome @agoose77. :-)

**Comment by douglasdavis** [comment]
@lgray This should be straightforward to add; would you happen to have a short example?

**Comment by lgray** [comment]
The most rudimentary example that is also immediately useful:
```
dask_record = uproot.dask({"some/nanoaod/file.root": "Events"})
dask_record = dask_awkward.with_parameter(dask_record, "metadata", {})
```

**Comment by douglasdavis** [comment]
P.S. in the case where an operation is relatively trivial; `dak.map_partitions` provides a generic API for applying an awkward function to a collection:

e.g.

```python
x = dak.from_parquet("file.parquet")
dak.num(x.some_field, axis=1)
```

can be represented with
 
```python
x = dak.from_parquet("file.parquet")
dak.map_partitions(ak.num, x.some_field, axis=1)
```

This may be useful for parts of the `ak.` namespace that don't currently have support in the `dak.` namespace. It's still useful for us to know which parts of `ak.` are needed!

**Comment by lgray** [comment]
We also do things like annotate doc strings and such.

**Comment by lgray** [comment]
Ah - using `dak.map_partitions` would be extremely disruptive to people currently doing analysis. It would be best to be a position where a user could `import dask_awkward as ak` and operations-wise be able to execute the same code.

We could do `dak.map_partitions` behind the scenes.

**Comment by douglasdavis** [comment]
> We could do dak.map_partitions behind the scenes.

Right, it's a bit more of an intermediate-user feature. A lot of the `dak. <--> ak.` connection is made with `map_partitions`.

**Comment by lgray** [comment]
In any case - we do a huge amount of array metadata manipulation and restructuring in NanoEvents having all the facilities to  all of that through dask-awkward is where I'd like to be at, since it would be a good factorization.

To get a basic idea of the interface:
https://www.youtube.com/watch?v=McKSS_WjLwU&t=1346s

It looks like once we get some of the more basic pieces in place it's not going to be hard at all (though I have a question about numba functions and dask, hopefully these aren't incompatible).

**Comment by douglasdavis** [comment]
numba functions and dask are indeed compatible

**Comment by douglasdavis** [comment]
`with_parameter` and `without_parameters` are in [`2022.11a2`](https://pypi.org/project/dask-awkward/2022.11a2/)

**Comment by lgray** [comment]
@douglasdavis moving further a bit on this - does dask_awkward want to support the usual notion of array typing in awkward?

If I, for instance, do `print(x.type) if x is a dask_awkward array then I get as an error:
```Traceback (most recent call last):
  File "testing.py", line 10, in <module>
    print(y.type)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 927, in __getattr__
    if self._maybe_behavior_method(attr):
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 912, in _maybe_behavior_method
    res = getattr(self._meta, attr)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/highlevel.py", line 460, in type
    self._layout.form.type_from_behavior(self._behavior), len(self._layout)
TypeError: 'UnknownLengthType' object cannot be interpreted as an integer
```
whereas `print(x.compute().type)` could give:
```
40 * event
```

This is often helpful for debugging types or generally a user knowing what they are dealing with at any given moment. I think it's OK that the length may be unknown, but the type of thing being indexed is really important!

**Comment by douglasdavis** [comment]
Lindsey Gray ***@***.***> writes:

> @douglasdavis moving further a bit on this - does dask_awkward want to
> support the usual notion of array typing in awkward?

Definitely! What you show below is a known issue. We need the
`Array.type` call to _not_ depend on length if the underlying layout is
a typetracer layout (because we rely on the "typetracer Array", which is
a length-less highlevel `Array` object).

This is just a guess.. but
maybe https://github.com/scikit-hep/awkward/pull/1849 will help here. cc
@agoose77 - he might have a non-guess answer :)

> If I, for instance, do `print(x.type) if x is a dask_awkward array then I get as an error:
> ```Traceback (most recent call last):
>   File "testing.py", line 10, in <module>
>     print(y.type)
>   File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 927, in __getattr__
>     if self._maybe_behavior_method(attr):
>   File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py", line 912, in _maybe_behavior_method
>     res = getattr(self._meta, attr)
>   File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/highlevel.py", line 460, in type
>     self._layout.form.type_from_behavior(self._behavior), len(self._layout)
> TypeError: 'UnknownLengthType' object cannot be interpreted as an integer
> ```
> whereas `print(x.compute().type)` could give:
> ```
> 40 * event
> ```
>
> This is often helpful for debugging types or generally a user knowing
> what they are dealing with at any given moment. I think it's OK that
> the length may be unknown, but the type of thing being indexed is
> really important!

**Comment by douglasdavis** [comment]
What we'll use to support the `type` property will just be `x._meta.type`:

```python
class Array:
    ...

    @property
    def type(self):
        return self._meta.type

    ...
```

but this problem would show up:

```python
In [4]: a = dak.from_lists([[1,2,3],[4]])

In [5]: a._meta
Out[5]: <Array-typetracer type='?? * int64'>

In [6]: a._meta.type
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [6], line 1
----> 1 a._meta.type

File ~/.pyenv/versions/3.10.8/envs/dev/lib/python3.10/site-packages/awkward/highlevel.py:460, in Array.type(self)
    448 @property
    449 def type(self):
    450     """
    451     The high-level type of this Array; same as #ak.type.
    452 
   (...)
    457     wrapped by an #ak.types.ArrayType.
    458     """
    459     return ak.types.ArrayType(
--> 460         self._layout.form.type_from_behavior(self._behavior), len(self._layout)
    461     )

TypeError: 'UnknownLengthType' object cannot be interpreted as an integer
```

**Comment by douglasdavis** [comment]
Ok you got me to dig a little more into this 😛. We would be able to support `.type` with this implementation:

```python
@property
def type(self):
    t = ak.types.ArrayType(a._meta._layout.form.type_from_behavior(a._meta._behavior), 0)
    t._length = "??"
    return t
```
This feels very hacky!

**Comment by douglasdavis** [comment]
Thanks, @agoose77!

**Comment by lgray** [comment]
Another one kind of in this vein: when `__doc__` is set in an awkward array's parameters it's forwarded to ipython/jupyter help and this is a pretty useful tool to have when poking around one's data.

Typically we fill the `__doc__` with the TTree's or TBranch's title, but it could be used for all sorts of information or helpful hints. Could this functionality be added at the dak level as opposed to having to go through `compute()` to get it?

Example of it not forwarding info presently:
```
In [5]: z = y.compute()

In [6]: z?
Type:            NanoEventsArray
String form:     [<NanoEventsRecord {run: 1, luminosityBlock: 13889, ...} type='event'>, ...]
Length:          40
File:            ~/coffea-dev/coffea/coffea/nanoevents/methods/base.py
Docstring:       Events
Class docstring:
NanoEvents mixin class

This mixin class is used as the top-level type for NanoEvents objects.

In [7]: y?
Type:        Array
String form: dask.awkward<with-parameter, npartitions=1>
Length:      40
File:        ~/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/dask_awkward/lib/core.py
Docstring:  
Partitioned, lazy, and parallel Awkward Array Dask collection.

The class constructor is not intended for users. Instead use
factory functions like :py:func:`~dask_awkward.from_parquet`,
:py:func:`~dask_awkward.from_json`, etc.

Within dask-awkward the ``new_array_object`` factory function is
used for creating new **instances.**
```

This is a trivial example, for most NanoAOD arrays the branch titles are a bit more explanatory. I know this is a bit of a creature comfort, but people use it when doing analysis.

**Comment by lgray** [comment]
An in particular the `dask_awkward` version of the form/layout doesn't say what it is expected to be once computed, which may be confusing. Perhaps we can say "dask-awkward proxy for XYZClass" or something to that effect?

**Comment by jpivarski** [comment]
> when `__doc__` is set in an awkward array's parameters

@lgray is referring to https://github.com/scikit-hep/uproot5/pull/784.

**Comment by lgray** [comment]
Cool with https://github.com/scikit-hep/uproot5/pull/784 more of nanoevents works right out of the box in terms of generating schemas and object description.

@agoose77 @douglasdavis This brings me to the next issue which is how do I change the form of a dask-awkward object that I've gotten from `uproot.dask` or `dak.from_parquet` ?

**Comment by lgray** [comment]
@agoose77 for that I mean that I get an awkward form from `uproot.dask`, then I have a set of rules to transform that form (and behavior) into something that represents the data with a different structure, but the same underlying inputs.

As a simple example, NanoEvents' NanoAODSchema would take {'nPhoton', 'Photon_pt', ...} (everything related to "Photon" as an expected naming scheme), and then change the access pattern from: `tree.Photon_pt` to `tree.Photon.pt`, creating a more "physics-object"-like interpretation of the data that's easier for most analysts to deal with. This requires creating nested forms describing nested record arrays and corresponding altering of behaviors.

**Comment by douglasdavis** [comment]
Pretty much anything that can be done to a concrete awkward array can be done to a dask-awkward collection. (exceptions include things that would have to cross partition boundaries- some of those are possible but we haven't prioritized that at this point). Whatever you do to an awkward array to change the access pattern from `tree.Photon_pt` to `tree.Photon.pt` we can do to the collection via a `map_partitions` call; this would simultaneously be applied to the collections metadata (a high level concrete awkward array with no real data attached to it). Does this help answer?

**Comment by lgray** [comment]
Ah - that's what I was missing `map_partitions` is also taking care of array metadata alterations?
If not, what is?

I think another way to ask the question is: how do I create new fields in a dask RecordArray (I see with_field isn't there yet) that may be then also nested collections of more dask RecordArrays?

I see dak.zip is there for part of this!

**Comment by lgray** [comment]
Ah - right I can just nest all the zips and do what I need to do.

If I do:
```
thing = map_partitions(fn, stuff)
array = dak.zip({"thing": thing, <other dak arrays>}, behavior=behavior, <opts>)
```

I'll get what I expect in terms of user-facing functionality for the zipped-up array?

**Comment by douglasdavis** [comment]
Yeah `map_partitions` will create a new metadata by applying the callable to the existing metadata

For example (some comments inline):

```python
In [9]: a
Out[9]: [[1, 2, 3], []]

In [10]: b
Out[10]: [[], [4, 5]]

In [11]: c = dak.from_lists([a, b])

In [12]: c
Out[12]: dask.awkward<from-lists, npartitions=2>

In [13]: c._meta
Out[13]: <Array-typetracer type='?? * var * int64'>

In [14]: d = dak.mean(c, axis=1)  # <--- map partitions call!

In [15]: d._meta  # <--- new collection here created by the previous call (building up a task graph), meta reflects the update
Out[15]: <Array-typetracer type='?? * float64'>

In [16]: d.compute()
Out[16]: <Array [2, nan, nan, 4.5] type='4 * float64'>
```
now without dask (notice the '??' outer dimension unknown length is now a known int):
```python

In [17]: x = ak.from_iter(a + b)

In [18]: x
Out[18]: <Array [[1, 2, 3], [], [], [4, 5]] type='4 * var * int64'>

In [19]: ak.mean(x, axis=1)
Out[19]: <Array [2, nan, nan, 4.5] type='4 * float64'>
```

Here is the code in `map_partitions` that determines the new metadata: https://github.com/ContinuumIO/dask-awkward/blob/efafe3efc066d207c32d53abfe3c83a5239c487a/src/dask_awkward/lib/core.py#L1270-L1281

it just applies the `fn` passed to `map_partitions` on the meta(s) (`fn(*metas, **kwargs)`)

**Comment by lgray** [comment]
As a side node - `dak.with_field` is going to be used by an awful lot of people, as is `dak.combinations`. Probably worth it to sort those out sooner rather than later.

**Comment by lgray** [comment]
Another way to put what I'm looking for is do you expect to expose an interface like `ak.from_buffers` where it takes an awkward form and some mapping to arrays and produces a high level array for you?

This is something library developers have been using so far in awkward.

**Comment by lgray** [comment]
Looks like `from_map` maybe but I am not sure.

**Comment by douglasdavis** [comment]
> is there any way to pass a form + a record / collection of dask arrays and have it then generate a new dask array from that?

I have a feeling this shouldn't be too difficult. I can think of two avenues

1. If we have some data source we have the `from_map` API which is similar to map_partitions but it creates (from scratch) a collection from a function instead of building from an existing task graph.

So if you have a function that reads a source and and gives it some form (or determines the form based on the input), we can also write:

```python
def get_data(source) -> ak.Array:
    array = some_factory()
    array = update_form(array)
    return array


from dask_awkward.lib.io.io import from_map

lazy_array = from_map(get_data, [file1, file2, ...], ...)
```

`uproot.dask` uses `from_map`.

2. You can write a function that updates the form of an example concrete array and use `map_partitions`. Here's an example where the existing metadata is used to determine what the new form should be using some other function:

```python
def update_form(array, form):
    ...
    return new_array

lazy_array = some_factory()
new_form = figure_out_form(lazy_array._meta)

fn = partial(update_form, form=new_form)
new_lazy_array = lazy_array.map_partitions(fn)
# or map_partitions(fn, lazy_array)

```

**Comment by lgray** [comment]
Yeah - I think the thing I actually want is the functionality of `ak.from_buffers` (or something very close to it) where I can specify the record arrays I want simply from the form and some array source (that obeys the Mapping interface)
Especially since in the awkward form you specify how/where to access the array you are interested in.

This would be especially clean with dask_awkward since it already does the abstraction of the underlying file type for us.

`ak.from_buffers` is what we've used for the longest time with awkward-1.0 to define and manipulate array shapes to produce physics objects, a similar interface in dask_awkward makes sense.

I guess that boils down to - `update_form` above should be part of dask_awkward since it's a general operation, and it looks like it's really implementing all or most of `ak.from_buffers`.

@jpivarski - please confirm?

**Comment by lgray** [comment]
The workflow looks something like:
```
base_array = opener("some/file/some/where.something") # uproot.dask or dak.from_<serialized format>
desired_form = apply_schema(base_array, specified_schema) # this is in derived library code (e.g. nanoevents)
desired_array = remapping(base_array, desired_form) # this is presently done with ak.from_buffers
user_function(desired_array)
```

**Comment by douglasdavis** [comment]
Thanks for the little workflow! In that example would you expect the `remapping` function use `ak.to_buffers(base_array)` and return `ak.from_buffers(...)` in its body?

**Comment by lgray** [comment]
Yes, and that is exactly what we do here within coffea (this is in awkward-1.0, so the analogues of what would be done in dask):
https://github.com/CoffeaTeam/coffea/blob/master/coffea/nanoevents/factory.py#L382-L397

Many, actually nearly all, of the functionality we have in coffea (as presently awkward-1.0) for mapping to files and abstracting data to arrays suits dask_awkward much better.

**Comment by douglasdavis** [comment]
Great, thanks for the explanation. I think we have one piece of the puzzle with: https://github.com/ContinuumIO/dask-awkward/blob/76860c2343058ca5693ce5756d026ce001cc6122/src/dask_awkward/lib/core.py#L1700-L1708

using it will ensure whatever new collection that gets created will have the proper `_meta` attr

**Comment by lgray** [comment]
There we go - thank you for translating concepts for me! This is quite a bit of the missing piece.

**Comment by jpivarski** [comment]
I hadn't been thinking of `from_buffers` as a function that would be "dak-able," but I can see how it occupies a central place. It is the most flexible way to make new arrays, and some things would have been implemented using it if they hadn't come first.

I suppose that a `dak.from_buffers` would be possible, taking `dask.array` values in the dict, assuming that they're partitioned in a compatible way. But it doesn't sound to me like that's the direction you're headed with this.

**Comment by lgray** [comment]
Ah - small misreading. We don't use `to_buffers` at all but instead we build up the form and its various keys from the TTree metdata and then `from_buffers` that.

**Comment by lgray** [comment]
I suppose one question is if you want to make `typetracer_from_form` a public interface, it's not exported at present so I'm not sure how much I want to build off of it. I can certainly prototype something up, will be ready to change a lot if necessary.

**Comment by lgray** [comment]
@jpivarski Not sure what the direction we are heading is very precisely yet. At least now I can get a type tracer built for a specialized NanoEvents schema and see what's missing from there. I suspect a more concrete picture will appear fairly soon.

**Comment by jpivarski** [comment]
We have talked about that, and the technique (but not a public API for it) has turned up in Uproot as well:

https://github.com/scikit-hep/uproot5/blob/b36a0229391c00e101fdbfd56925afa9e2bd2ebb/src/uproot/_dask.py#L610-L613

For now, the fact that this is "One Weird Trick" and not a specialized function in Awkward is less than ideal, but not a high priority because it's easy to implement and won't change.

**Comment by douglasdavis** [comment]
> I suppose one question is if you want to make typetracer_from_form a public interface, it's not exported at present so I'm not sure how much I want to build off of it. I can certainly prototype something up, will be ready to change a lot if necessary.

I think `dak.typetracer_from_form` is a good addition

**Comment by lgray** [comment]
My next question is then: how do I take the type tracer and turn it into something that I can do:
`events.Photon.pt.compute()`
on?

**Comment by douglasdavis** [comment]
You'll want a collection that is represented by your `events` typetracer. However you overwrite the form of a real awkward array (not a typetracer) you'll need to apply to the collection as a step in a task graph

I'm guessing you get `z` from somewhere in this workflow and `data` from somewhere in this workflow:
```python
def overwrite_form(concrete_ak_array, form):
    # do something that changes the form of some _real_ data (i.e. ak.from_buffers(form=...,))
    # overwritten = ak.from_buffers(form, ..., some_use_of_concrete_ak_array)
    return overwritten

data = uproot.dask(...)
z = something()
desired_form = z[1]._form
new_typetracer = dak.typetracer_from_form(desired_form)
data.map_partitions(overwrite_form, desired_form, meta=new_typetracer)
```
If `data` has the same fields as your `data.fields` you should now be able to do
```
data.Photon.pt.compute()
```
Now the `data` collection has the proper typetracer and

**Comment by lgray** [comment]
OK - this perhaps exposes a bit of a problem.
What I want to be able to do is use dask's lazy evaluation to read *only* the data that is asked for by the end-user analysis.
Since NanoEvents describes the entire transformed data frame it would cause the reading of all the data when we ask for `ak.from_buffers`, which is definitely not what we want.

What could be done, strangely enough, is to use the original `data = uproot.dask` as the data mapping and use the form keys to extract what we expect (and call compute, when/if needed).

Or is there a pleasant way to extract the data that is actually desired by the user?

**Comment by douglasdavis** [comment]
Hmm. So we have a column projection optimization that will ensure only necessary columns are read from a dataset (all in this module https://github.com/dask-contrib/dask-awkward/blob/main/src/dask_awkward/lib/optimize.py). uproot.dask already benefits  from this.

For example say `file.root` has a `tree` with 100 branches: `col{001-100}`. If I use `uproot.dask` without specifying the branches I want, we will automatically read _only_ `["column001",  "column100"]` with this workflow (the optimization happens during compute):
```python
data = uproot.dask({"file.root": "tree"})
thing = data.column001 + data.column100
thing.compute()
```

The fact that you remap events_Photon_pt to events.Photon.pt may be a problem for what is currently implemented, I'm not sure.

**Comment by lgray** [comment]
Coming back to this - are there specific reasons you cannot use the "form_key" property of the form to separate what you're calling the data members in code from how they are located on disk? 

This is how it was done with the awkward-1.0 and I think the pattern still applies just fine?

@jpivarski commentary?

**Comment by jpivarski** [comment]
The "form_key" mechanism hasn't changed. (The only v1 → v2 change in that area is that the arguments to `from_buffers` for constructing buffer names from form keys has been simplified. In particular, there's no "part#-" substring for partitions, since there are no partitions anymore.)

I've been reading these comments, and I don't see how the form key could be used to solve this problem. If you did have a solution that leveraged form keys, it should still work, but I don't know how that would have been done.

**Comment by lgray** [comment]
Oh - my thinking was that the form key could encode/describe the data product you want to read from the original source file regardless of how it is nested in the dask_awkward object that's being made on top of it. Essentially being the connection to the raw data for dask's io layer to deal with.

**Comment by jpivarski** [comment]
In order to do this column-removal optimization, (I _think_) Dask needs to know the difference between a source node and other nodes in its graph. But also, I asked about this at one of our meetings, and I remember @douglasdavis showing that the information exists and is being used. The Form's keys wouldn't be a place where that could go, since everything in the Form is source.

Is `uproot.dask` adding the metadata that distinguishes source nodes from other nodes, and @lgray needs to be told how to add that metadata? Is that all that's needed here?

**Comment by lgray** [comment]
In some sense the source nodes are already defined since I'm starting from `uproot.dask` and applying a new form off of that. Purely metadata changes. So I suppose all I am missing is the way to "forward" what uproot.dask has into however I've remapped it.

**Comment by douglasdavis** [comment]
`uproot.dask` indeed takes advantage of what I think you are calling the source node vs regular node difference. "Source nodes" are generated from `AwkwardIOLayer`s. The use of `dask_awkward.from_map` is where this happens (`from_map` will create an `AwkwardIOLayer`); the optimization searches for these layers.

**Comment by douglasdavis** [comment]
The way we determine the necessary branches is test if the task graph executes successfully when operating _only_ on metadata. So in theory, whatever operations you do _without_ dask can be done to the metadata, we should still be able take advantage of the optimization. This is truly the great power of typetracer arrays!

**Comment by douglasdavis** [comment]
Here is where we call `project_columns` such that we define only the necessary columns:

https://github.com/dask-contrib/dask-awkward/blob/3f30e0a7dc5725a4e3488507348d8793075ca772/src/dask_awkward/lib/optimize.py#L175

**Comment by lgray** [comment]
Thanks for going over this! What would be your proposed manner of implementing this with nanoevents? I could certainly implement something that does what is necessary but I would prefer to make sure I'm not reinventing wheels or otherwise choosing poor factorization. 

My first guess for this is to do something like:
- Have a class `_NanoEventsRemap` that creates the correspondence between the altered schema calls so I can just use `map_partitions` on it and therefore I can do (from above):
```python3
data = uproot.dask(<something>)
desired_form, new_typetracer = apply_schema(desired_form_maker, data.layout.form)
remap = _NanoEventsRemap(desired_form, <some args>)
data = data.map_partitions(remap, desired_form, meta=new_typetracer)
```

Where `_NanoEventsRemap` essentially stores the mapping from `events.Photon.pt` in the NanoEvents form to `Photon_pt` in the `uproot.dask` raw interpretation. So the internals of it would have to examine the type tracer to see what to actually call from?

I'm not entirely sure exactly how to do that, actually, since I don't quite see what dataformat the `_NanoEventsRemap` class `remap` instance would receive into `__call__`. I can certainly always just go find out but beter to ask first. There would need to be some functionality of generating new calls in the task graph on the fly (there are synthetic or otherwise augmented columns in NanoEvents for convenience).

**Comment by lgray** [comment]
If I should rather be just building my own mapping and circumventing uproot then we should say that now. I was very much under the impression I'd be able to put most of the handling of what's in the root file on the uproot/dask_awkward side of the fence.

**Comment by douglasdavis** [comment]
Lindsey Gray ***@***.***> writes:

> If I should rather be just building my own mapping and circumventing
> uproot then we should say that now. I was very much under the
> impression I'd be able to put most of the handling of what's in the
> root file on the uproot/dask_awkward side of the fence.

I don't think a custom mapping of data-on-disk -->
dask-awkward-collection is necessary, especially because `uproot.dask`
already handles column projection. I think the path you've started to
jot down is promising.

With this file here:
https://github.com/CoffeaTeam/coffea/blob/master/tests/samples/nano_dy.root?raw=true
can you write out a code snippet that implements `_NanoEventsRemap` for
the photon pt workflow on _eager_ data (don't worry about dask usage). I
can start playing with building a task graph and experiment with the
optimization.

**Comment by lgray** [comment]
So:
https://github.com/CoffeaTeam/coffea/blob/awkward2_dev/coffea/nanoevents/mapping/uproot.py

is the eager-mode implementation of this. It probably covers a bit too much in scope, but the main things to know are that:
- it constructs the desired form and applies it to data
- uses the form_key in the awkward array to specify where to get the data from and possibly any transformations to that data (with a rather small embedded DSL)

If you check out that branch of the coffea repo, do `cd coffea && pip install -e '.[dev]'` you can then run:
`pytest tests/test_nanoevents.py` (https://github.com/CoffeaTeam/coffea/blob/awkward2_dev/tests/test_nanoevents.py)

To have something to poke at. If you'd rather me extract it I can do that, but I figured the full implementation in-situ might be illuminating for you!

**Comment by lgray** [comment]
This is largely taken care of now.
