### ISSUE TITLE
`dak.unzip`

### ISSUE THREAD

**Issue by masonproffitt** [dask-contrib/dask-awkward#121]
Now that Uproot 5 (and thus `uproot.dask`) is officially released, I'm going to start making issues for these `NotImplemented` errors when I run into them:

```python
    @borrow_docstring(ak.unzip)
    def unzip(array, highlevel=True, behavior=None):
>       raise DaskAwkwardNotImplemented("TODO")
E       dask_awkward.utils.DaskAwkwardNotImplemented: TODO
E
E       If you would like this unsupported call to be supported by
E       dask-awkward please open an issue at:
E       https://github.com/dask-contrib/dask-awkward.
```

**Comment by masonproffitt** [comment]
The use case here is of course to be able to invert the `zip()` operation, which for me is mainly important for being able to access the individual members of tuples created by `combinations()` or `cartesian()`

**Comment by lgray** [comment]
I started working on this one and while I see a few hacky ways to deal with a tuple of arrays being returned, I couldn't really decide a nice way to do it given the current infrastructure. 

@douglasdavis I think the best way to do this is to maintain the appearance of the awkward interface which return `tuple(ak.Array)`, but it wasn't really clear to me how to make an efficient graph for this using `dask.HighLevelGraph` as there isn't any immediate documentation on indexing into returned products. I guess the evolution of the meta would also have to understand how to interpret the tuple.
