### ISSUE TITLE
`dak.concatenate`

### ISSUE THREAD

**Issue by masonproffitt** [dask-contrib/dask-awkward#123]
Not implemented:

```python
    @borrow_docstring(ak.concatenate)
    def concatenate(
        arrays,
        axis=0,
        merge=True,
        mergebool=True,
        highlevel=True,
        behavior=None,
    ):
>       raise DaskAwkwardNotImplemented("TODO")
E       dask_awkward.utils.DaskAwkwardNotImplemented: TODO
E
E       If you would like this unsupported call to be supported by
E       dask-awkward please open an issue at:
E       https://github.com/dask-contrib/dask-awkward.
```

**Comment by martindurant** [comment]
Of the incoming issues, I suggest this is the easiest one to support, for any value of `axis`. I'm not sure we would support all of the optional argiuments.

**Comment by masonproffitt** [comment]
The main use case here for me is for combining collections of similar objects that need the same operations applied to them, like putting electrons and muons together for applying identical lepton selections

**Comment by douglasdavis** [comment]
`axis>=0` support is in; we can handle future needs with another issue
