### ISSUE TITLE
`dak.argsort`

### ISSUE THREAD

**Issue by masonproffitt** [dask-contrib/dask-awkward#124]
Not implemented:

```python
    @borrow_docstring(ak.argsort)
    def argsort(
        array,
        axis=-1,
        ascending=True,
        stable=True,
        highlevel=True,
        behavior=None,
    ):
>       raise DaskAwkwardNotImplemented("TODO")
E       dask_awkward.utils.DaskAwkwardNotImplemented: TODO
E
E       If you would like this unsupported call to be supported by
E       dask-awkward please open an issue at:
E       https://github.com/dask-contrib/dask-awkward.
```

**Comment by martindurant** [comment]
This one will be *hard* :)

**Comment by masonproffitt** [comment]
There are many important use cases here. For example, selecting the leading object (e.g., jet with the highest pT) or finding the closest object to another (smallest deltaR)

**Comment by jpivarski** [comment]
For this one, I think that `argsort` with `axis=0` will be hard (because it's a distributed shuffle) but `axis>0` will not because it's just dispatched to all of the partitions independently. The use-case @masonproffitt probably has in mind is `axis=1`.

**Comment by lgray** [comment]
@masonproffitt and in fact this already works for axis > 0, you just have to specify a positive axis number. Would you prefer this only throw an error when `axis = -1` is the same as `axis = 0`?

**Comment by masonproffitt** [comment]
In `func-adl-uproot`, I always specify the non-negative axis value, so it doesn't matter much to me. But isn't that behavior exactly what #130 does anyway?

**Comment by lgray** [comment]
It doesn't protect against the innermost dimension being the same as axis=0.
