### ISSUE TITLE
`dak.broadcast_arrays`

### ISSUE THREAD

**Issue by masonproffitt** [dask-contrib/dask-awkward#128]
Not implemented:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask_awkward/lib/structure.py", line 108, in broadcast_arrays
    raise DaskAwkwardNotImplemented("TODO")
dask_awkward.utils.DaskAwkwardNotImplemented: TODO

If you would like this unsupported call to be supported by
dask-awkward please open an issue at:
https://github.com/dask-contrib/dask-awkward.
```

**Comment by martindurant** [comment]
@masonproffitt , it would be good if you could provide motivating use cases for these, so that we can try to prioritize our efforts. Obviously, we are already aware of which methods we have not implemented yet.

**Comment by masonproffitt** [comment]
The motivation for all of these is that they are the `awkward` functions used by [`func_adl_uproot`](https://github.com/iris-hep/func_adl_uproot/blob/174306406269f7a64df068483c76c566a7c4857a/func_adl_uproot/transformer.py). This means the code trying to run these functions is generated by that package, so the use cases are really in the FuncADL queries that prompt the code to be generated, which are maybe a bit abstract. But sure, I can try my best to explain the motivations for why the function is used in each case.

**Comment by masonproffitt** [comment]
The motivation for this one is basically coming from needing to add another field to an array, which in the `func_adl_uproot` cases is generally just broadcasting a scalar, so `dak.full_like()` (also not implemented) would probably work too.

**Comment by lgray** [comment]
This is used all over the place within coffea. It is necessary.
