### ISSUE TITLE
Field order is changed after `compute`

### ISSUE THREAD

**Issue by masonproffitt** [dask-contrib/dask-awkward#171]
#148 seems to no longer preserve the order of fields after `compute` (the exact file here is <https://github.com/iris-hep/func_adl_uproot/blob/aed2e68c6643bfc955ba45742874fe303201a467/tests/scalars_tree_file.root>):

```python
>>> import uproot
>>> u = uproot.dask('scalars_tree_file.root')
>>> u.fields
['int_branch', 'long_branch', 'float_branch', 'double_branch', 'bool_branch']
>>> u.compute().fields
['bool_branch', 'double_branch', 'float_branch', 'int_branch', 'long_branch']
```

It looks like the branches get alphabetized. Is this expected? Is there a way to enforce that the order is preserved? ROOT files have a fixed branch ordering, and there's plenty of code that relies on this fact.

**Comment by douglasdavis** [comment]
Mason Proffitt ***@***.***> writes:

> #148 seems to no longer preserve the order of fields after `compute` (the exact file here is <https://github.com/iris-hep/func_adl_uproot/blob/aed2e68c6643bfc955ba45742874fe303201a467/tests/scalars_tree_file.root>):
>
> ```python
>>>> import uproot
>>>> u = uproot.dask('scalars_tree_file.root')
>>>> u.fields
> ['int_branch', 'long_branch', 'float_branch', 'double_branch', 'bool_branch']
>>>> u.compute().fields
> ['bool_branch', 'double_branch', 'float_branch', 'int_branch', 'long_branch']
> ```
>
> It looks like the branches get alphabetized. Is this expected?

We indeed use `set(...)` at some points in the code to write a new
`columns=` without repeating columns, which does sort things.

Off the top of my head I think it should only happen if the necessary
columns optimization is leveraged (I'm not sure though), can you try to
compute with

```python
with dask.config.set({"awkward.optimization.enabled": False}):
    u.compute().fields
```

And see if you get the same result?

> Is there a way to enforce that the order is preserved?

There's probably a way to do this. Would need to think more about it.

> ROOT files have a fixed branch ordering, and there's plenty of code
> that relies on this fact.

Can you give an example? Just want to wrap my head around relevant use
cases.

**Comment by masonproffitt** [comment]
> Off the top of my head I think it should only happen if the necessary columns optimization is leveraged (I'm not sure though), can you try to compute with
> ```python
> with dask.config.set({"awkward.optimization.enabled": False}):
>     u.compute().fields
> ```
> And see if you get the same result?

Yep, then I get the old/plain awkward behavior.

> Can you give an example? Just want to wrap my head around relevant use cases.

Almost of all of my tests rely on this, which is how I noticed 😅... but I don't off the top of my head know where actual analysis code might depend on this. I'm sure it's out there, though probably not exactly a best practice. I suppose it's mostly just very unexpected to me as a user that `array.compute().fields != array.fields`, or that `uproot.dask('file.root:tree').compute().fields != uproot.open('file.root:tree').arrays().fields`.

**Comment by agoose77** [comment]
@masonproffitt certainly from a UX perspective, Awkward would want `.fields` to be an ordered list. I don't know enough about why this is different in awkward-dask, but I am fairly confident we can change this, without speaking to Doug.
