### ISSUE TITLE
Possible bug: tests/test_0652_dask-for-awkward.py in uproot tests fails on dask_awkward main

### ISSUE THREAD

**Issue by lgray** [dask-contrib/dask-awkward#174]
Using dask_awkward main branch:
```python3
test_path = (
    skhep_testdata.data_path("uproot-sample-6.08.04-uncompressed.root") + ":sample"
)
ttree = uproot.open(test_path)
    
ak_array = ttree.arrays()
dak_array = uproot.dask(test_path, library="ak")

assert len(ak_array) == len(dak_array)
```
results in:
```
AssertionError: assert 30 == 0
+  where 30 = len(<Array [{n: 0, b: True, ab: [...], ...}, ...] type='30 * {n: int32, b: bool...'>)
+  and   0 = len(dask.awkward<from-uproot, npartitions=1>)
```

opening this here despite it possibly being in a deeper library @agoose77 @jpivarski

**Comment by douglasdavis** [comment]
On phone right now but I know where to start looking when I'm in front of a computer.

- [ ] Side note: this has come up in the past in another context-- uproot should be able to define the divisions of a collection in uproot.dask because the nentries in a root file are trivially accessible, right? Can uproot.dask define the divisions attr at collection instantiation time? Then 'len(array)' just becomes shorthand for 'array.divisions[-1]'

**Comment by douglasdavis** [comment]
Found part of the issue

```python
In [1]: import dask.config
   ...: import uproot, skhep_testdata

In [2]: test_path = (
   ...:     skhep_testdata.data_path("uproot-sample-6.08.04-uncompressed.root") + ":sample"
   ...: )
   ...: ttree = uproot.open(test_path)
   ...: 
   ...: ak_array = ttree.arrays()
   ...: dak_array = uproot.dask(test_path, library="ak")

In [3]: with dask.config.set({"awkward.optimization.enabled": True}):
   ...:     print(dak.core.calculate_known_divisions(dak_array))
(0, 0)

In [4]: with dask.config.set({"awkward.optimization.enabled": False}):
   ...:     print(dak.core.calculate_known_divisions(dak_array))
(0, 30)
```

The optimization is telling ROOT not to read any branches, so we get length zero

**Comment by lgray** [comment]
Cool confirmed fixed in the in-situ uproot tests. Could we now mint a release? Then I can get https://github.com/scikit-hep/uproot5/pull/834 merged.

**Comment by douglasdavis** [comment]
2023.2.2 is out :+1:
