### ISSUE TITLE
Trying to call a behavior method fails with `unexpected keyword argument '__dask_array__'`

### ISSUE THREAD

**Issue by masonproffitt** [dask-contrib/dask-awkward#193]
Example:

```python
>>> import awkward as ak, dask_awkward as dak, vector
>>> vector.register_awkward()
>>> a = ak.Array([{'x': 1, 'y': 1}])
>>> da = dak.from_awkward(a, 1)
>>> dv = dak.with_name(da, 'Vector2D')
>>> dv.deltaphi(dv)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/core.py", line 990, in wrapper
    return self._call_behavior_method(attr, *args, **kwargs)
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/core.py", line 932, in _call_behavior_method
    return getattr(self._meta, method_name)(
TypeError: Planar.deltaphi() got an unexpected keyword argument '__dask_array__'
```

The plain `awkward` version works as expected:

```python
>>> v = ak.with_name(a, 'Vector2D')
>>> v.deltaphi(v)
<Array [0] type='1 * float64'>
```

**Comment by douglasdavis** [comment]
Looks like this is related to @lgray's work on making behaviors tunable w.r.t. use with and without dask-awkward. I'll dig into a bit, it may be a case of us just needed to check if the attribute exists

**Comment by lgray** [comment]
Ah, the vector package will need a PR to capture the correctly.

**Comment by lgray** [comment]
Ah, I have a better solution. I'll make a PR to `dask_awkward` tomorrow.

**Comment by agoose77** [comment]
> @masonproffitt to allow callbacks to unindexed arrays or other arrays when making the task graph, all behavior methods are assumed to be able to take __dask_array__ defaulted to None as an argument. Just add that variable to your function arguments and you'll be good to go.

@lgray your last message implies that you might be changing tack, but for posterity; if we can do this without requiring existing behaviours to opt-in, that would be ideal. By default, we should hope that much will just work no additional efforts on the part of extension authors.

I wouldn't hate the idea that `dask-awkward` inspect the function signature and look for a keyword-only argument for `__dask_array__` (if that's the API we're aiming for). 

However, the idea of an additional function argument won't work for property descriptors, which we should try to support too. I can also give this some thought!

**Comment by lgray** [comment]
@agoose77 I already have a thing in place for properties, see the comments in respective portions of code. 

Basically, if someone wants to pass in some other array to do something with, I use:
```python3
def get_the_property(args, __dask_array__=None):
   do stuff
   return something

the_property = property(get_the_property)
```

And if they don't define `get_the_property` then it wraps the property supplying no other arrays.

As for regular methods yes, exactly, I intend to inspect the arguments list for `__dask_array__` dynamically so opt-in is easier.

**Comment by agoose77** [comment]
> @agoose77 I already have a thing in place for properties, see the comments in respective portions of code.

Oh, this is [already in dask-awkward](https://github.com/dask-contrib/dask-awkward/blob/bc38a8fb09aef335a5fe88da1a9d6a41c21e953c/src/dask_awkward/lib/core.py#L924-L967).

This approach requires a naming convention which in-turn imposes a restriction on the behaviour class (i.e. `get_XXX` names become reserved).

I wonder if it might be better to introduce a decorator into `dask-awkward` that allows us to e.g.
```python

class Behavior:
    @dak.property
	def some_value(self, __dask_array__):
        ...
```

This would allow behaviour authors to gracefully opt-in. This would introduce a dependency upon `dask-awkward` for these libraries, although that's already implicitly true.

Alternatively, we could do this via introspection again:
```python
class Behavior:
    @property
	def some_value(self, __dask_array__=None):
        ...
```

`dask-awkward` would then invoke 
```python
getter = Behavior.some_value.fget.__get__(array._meta)
getter(__dask_array__=array)
```

**Comment by lgray** [comment]
I can try those out in the next week or so! Or feel free to implement yourself.

**Comment by lgray** [comment]
Actually, as far as implementation is concerned, I can see people wanting to pass a multitude of "callback arrays" before various transformations or what have you (even fusing graphs?). 

@douglasdavis @agoose77 would you be OK with all `__dunder__` arguments to dask_awkward behavior methods/properties following this rule or is it too greedy? I personally think it's cleaner to reserve a class of naming variables to certain expectations about their function, rather than just taking `__dask_array` for instance.

**Comment by agoose77** [comment]
@lgray it's getting late here so I might not be processing this very well! Could you perhaps reword your question?

As for the general query; I prefer reserving sunder names (which is a precedent) rather than restricting the available public namespace. So, even though I've suggested `__dask_get__`, a better name would be `_dask_awkward_get_`.

**Comment by douglasdavis** [comment]
I do agree with @agoose77 on using dunder names when possible in a case like this if it's do-able (w.r.t. avoiding reserving non-dundered names). I also agree with Angus on not having the easiest time processing the question! But with that said, I am in general good with going in any direction that best serves making dask-awkward behavior usage work well for existing users of awkward behaviors.

**Comment by douglasdavis** [comment]
(accidental close)

**Comment by lgray** [comment]
If you can wait two days I can probably have a much better interface worked out by Friday.

We've all been waiting for this for four years, I don't think that's a significant delay.

**Comment by agoose77** [comment]
@douglasdavis it sounds like the answer is yes, so I'm happy to hold off?

If it's a question of moving from one breakage to another, both aren't brilliant, and I'd err on the side of inactino.

**Comment by lgray** [comment]
If you can find someone to do my management work for me (looks suspiciously at ChatGPT), I'd already be on a fix! or similarly if someone wants to provide a fix for both sides earlier than I am able!

**Comment by agoose77** [comment]
@lgray I would myself be doing this right now, but deadlines are crazy the next week and a bit!!

**Comment by douglasdavis** [comment]
Since this would break things I say we indeed do not revert-- theres no rush here; I just wasn't sure if you were using that feature yet!
