### ISSUE TITLE
Implement remaining `ak.X` transformations in `dak`

### ISSUE THREAD

**Issue by lgray** [dask-contrib/dask-awkward#205]
This is an issue to keep track of implemented functions at the upcoming CMS CAT hackathon.
There are a few remaining that aren't in dak that people use in analysis.

@andrzejnovak

**Comment by douglasdavis** [comment]
It's been a while since we've seen a missing ak.X function, so I'll go ahead and close this. We ought to be able to handle individual missing implementations in their own issues
