### ISSUE TITLE
Fuse `getitem` calls that are only `str` or `tuple[str]` arguments at graph building time

### ISSUE THREAD

**Issue by douglasdavis** [dask-contrib/dask-awkward#206]
See discussion here: https://github.com/dask/dask/issues/9795#issuecomment-1494447562

It would be useful to combine these layers _before_ the upstream blockwise optimization

**Comment by douglasdavis** [comment]
@martindurant this can be closed, right?

**Comment by martindurant** [comment]
Yes, this will be covered by the general linear fusing, although I don't think we have an explicit test for it.
