### ISSUE TITLE
feature request: dak.to_dask_dataframe ?

### ISSUE THREAD

**Issue by raybellwaves** [dask-contrib/dask-awkward#208]
I'm working on https://github.com/intake-dynamodb/intake-dynamodb/pull/4. see also https://dask.discourse.group/t/dd-from-dict-giving-typeerror/1714

What would be the best way to convert a dask_awkward.lib.core.Array to dask.DataFrame ?

Upstream there is a `ak.to_dataframe(ak_array)` method. Should there be a `dak.to_daskdataframe` method?

```
dak_array = dak.from_json("s3://bucket/AWSDynamoDB/HASH/data/*.json.gz")
ddf = dak.to_daskdataframe(dak_array) # ?
```

**Comment by martindurant** [comment]
This may be blocked until we can integrate awkward-pandas with dask.dataframe. For now, I suppose you can `.map_partitions(ak.to_dataframe)` ?

**Comment by douglasdavis** [comment]
@martindurant- yes that's what I'm handling so far- the naive case of just map_partitioning an awkward array; we'll definitely want to integrate the extension type as a next step

**Comment by jpivarski** [comment]
(I lost my comment to a power outage!)

How about if we use these names:

  * `ak.to_dataframe` (exists): `ak.Array` → `pd.DataFrame` by exploding lists and records into MultiIndex and columns
  * `ak.to_series` (new): `ak.Array` → `pd.Series` by directly wrapping it with [awkward-pandas](https://github.com/intake/awkward-pandas)
  * `dak.to_dataframe` (what @raybellwaves is requesting): `dak.Array` (Dask) → `dd.DataFrame` (Dask) by explosion
  * `dak.to_series` (possible extrapolation): `dak.Array` (Dask) → `dd.Series` (Dask) by combining dask-awkward with awkward-pandas

?

**Comment by douglasdavis** [comment]
Yes I like that naming scheme 👍

**Comment by raybellwaves** [comment]
Thanks!

**Comment by douglasdavis** [comment]
Absolutely! We're continuing to work on awkward-pandas-dask interop with https://github.com/intake/awkward-pandas/pull/30 as well
