### ISSUE TITLE
suggest pip install -e .[test] ?

### ISSUE THREAD

**Issue by raybellwaves** [dask-contrib/dask-awkward#212]
See https://dask-awkward.readthedocs.io/en/stable/dev-contributing.html#adding-code

Should it say "pip install -e ".[test]" ? as the next line is pytest

**Comment by douglasdavis** [comment]
Thanks for raising! Yea, and after thinking about it a bit more I think in the dev docs we should perhaps have both test and docs, I'll update these instructions
