### ISSUE TITLE
Automate wrapping of float/int in awkward operations

### ISSUE THREAD

**Issue by yimuchen** [dask-contrib/dask-awkward#226]
There are certain operations that fail when passing in a float or int object 

```python
import awkward as ak
import dask_awkward as dak
import numpy as np

arr = ak.zip({
    'x': ak.from_regular(np.random.random(size=(10, 10))),
    'y': ak.from_regular(np.random.random(size=(10, 10)))
})
arr = dak.from_awkward(arr, npartitions=1)

arr = dak.where(arr.x > 0.5, 1.0, arr.y) # 'float' object has no attribute 'npartitions'
arr['z'] = 2.0 # DaskAwkwardNotImplemented: Supplying anything other than a dak.Array to __setitem__ is not yet available!
```

The user side solution is rather simple, instead of floats or int, we wrap it in `dak.ones_like(arr.x) * <int>`, but it would be nice if this can be handled automatically.

**Comment by lgray** [comment]
So nominally we can `map_partitions` inputs so long as they broadcast correctly.

I'm starting a PR to see if we can fix this up.
