### ISSUE TITLE
dask_awkward tests fail with dask 2023.4.0

### ISSUE THREAD

**Issue by lgray** [dask-contrib/dask-awkward#231]
To be seen if this requires repinning, etc.

**Comment by lgray** [comment]
This appears to be caused by this commit in dask:
https://github.com/dask/dask/commit/ec3ffedff7bfbad93fe582adf21c71ca9f0b064b

Where they removed the `__distributed_pack__` and variations. No idea why.

**Comment by martindurant** [comment]
OK, so we have to make sure things can serialise normally with pickle.
