### ISSUE TITLE
Several functions (including dak.max) incorrectly raise awkward._errors.FieldNotFoundError

### ISSUE THREAD

**Issue by jrueb** [dask-contrib/dask-awkward#260]
Please consider the following
```python
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema
import dask_awkward as dak

events = NanoEventsFactory.from_root(
    "https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root",
    metadata={"dataset": "DoubleMu"},
    schemaclass=NanoAODSchema,
    permit_dask=True,
).events()
pt = events["Muon"]["pt"]
print(dak.max(pt).compute())
```
This will raise an error `awkward._errors.FieldNotFoundError: no field 'pt' in record with 1 fields`.
This error should not happen. `print(ak.max(pt.compute()))` works fine.
I've also observed the error with `dak.min` and `dak.is_none`.

dask_awkward version 2023.5.0
awkward version 2.2.0
Coffea version 2023.4.0.rc3

**Comment by lgray** [comment]
@jrueb it would help if you can reproduce this without coffea to pin down where the error is. Usually stuff like this ends up being related to typetracers, which is actually down in awkward.

You can see an example of making some fake data to play with, using a form, here:
https://github.com/scikit-hep/awkward/issues/2416

Then you can work up to dask_awkward and a file if there's no problem in awkward itself, etc.

**Comment by lgray** [comment]
Related to #256

**Comment by agoose77** [comment]
I think this can be closed now?

**Comment by jrueb** [comment]
> I think this can be closed now?

It seems there was a conclusion in https://github.com/scikit-hep/awkward/issues/2463, which I can't fully follow. If this is a wontfix, how would I have to adjust my code in order to fix this?

**Comment by lgray** [comment]
This can't be closed now because the fix is getting unproject_layout to work correctly, which we've had to revert for now because it doesn't. We are definitely fixing this, just taking longer and with more churn than thought at first. I would mark the underlying issue a priority for August @agoose77 @douglasdavis.

**Comment by douglasdavis** [comment]
Yeah this isn't something where we can suggest an adjustment to the failing code (except to turn off column optimization, which is absolutely undesireable). @lgray summarized the situation -- I'm currently working on figuring out the bugs in `unproject_layout`/"form rehydration"

**Comment by douglasdavis** [comment]
Main issue being tracked in #313
