### ISSUE TITLE
`ak.concatenate(..., axis=0)` should not touch any data

### ISSUE THREAD

**Issue by agoose77** [dask-contrib/dask-awkward#305]
We can (and technically do) implement this as a growth in the number of partitions.

**Comment by iasonkrom** [comment]
@agoose77 @douglasdavis I just wanted to ask if this idea is still alive and its current status. I’m just thinking about something in my code.

**Comment by agoose77** [comment]
This is and I'm working on it!

It looks like we need a new function, `enforce_form` to do this.

**Comment by agoose77** [comment]
Jim and I spoke about this, and settled on the initial implementation having the following semantics:
1. `ak.concatenate(..., axis=0)` for some sequence of arrays with identical forms should just build a logical union (`dak.Array`)
2. `ak.concatenate(..., axis=0)` for some sequence of arrays with _different_ forms should use `ak.enforce_type`. At the end of the day, this will really only penalise the case where all partitions have one of two forms, neither of which is canonical.

**Comment by agoose77** [comment]
@douglasdavis I started playing around with this, and realised I was missing a point RE optimisation.

Do you think it's feasible to optimise `ak.concatenate(..., axis=0)` such that we don't _actually_ concatenate at worker time unless all of the collection partitions are required? e.g., could we optimise
```python
dak.concatenate((x, y)).z[0]
```
to only compute `x.z[0]`?

**Comment by douglasdavis** [comment]
Without testing it out, I think this would automatically optimize based on
upstream dask’s task culling (that is, we shouldn’t have to do anything).
the zero getitem call will trigger dask awkward to make a layer that only
needs the first partition, and Dask should do the rest. dask.visualize(…,
optimize_graph=True) should be able to prove it!
