### ISSUE TITLE
Empty and Ellipsis slices are interpreted incorrectly

### ISSUE THREAD

**Issue by jrueb** [dask-contrib/dask-awkward#322]
I would like to create a simple copy of an array, but the usual syntax of an empty slice is not working.

To reproduce
```python
import awkward as ak
import dask_awkward as dak

a = dak.from_awkward(ak.Array({"x": [1,2,3]}), 1)
b = a[:]
b["y"] = dak.from_awkward(ak.Array([4,5,6]), 1)
print(a.fields)
```
I expect it to print `['x']`. However it actually prints `['x', 'y']`, which indicates `a` and `b` are actually the same object. Indeed `id(a) == id(b)` is true. The same issue appears with `b = a[...]`. In Awkward the behavior is as expected.

Tested on the latest main branch.

**Comment by douglasdavis** [comment]
This is a non-trivial area in the Dask universe. We take inspiration from `dask.array.Array` where the `Array` collection is immutable; so `[:]` and `[...]` just return the existing collection. `dask.array` differs from it's mirroring project (numpy) in this way

```pycon
>>> import dask.array as da
>>> a = da.random.standard_normal(10000, 1000)
>>> a[...] is a
True
>>> a[:] is a
True
```

**Comment by martindurant** [comment]
I am ambivalent on whether we want to preserve the object like that, but if so, copy.copy() should be made to work (as in the other issue) and that can be our recommendation.

**Comment by martindurant** [comment]
#324

**Comment by jrueb** [comment]
Thanks for the quick replies. Now with `copy.copy` fixed and this being the intended behavior, I do not have further issues regarding this.
