### ISSUE TITLE
`events[boolean mask]` computes fail with `scheduler="processes"` or a distributed `Client`

### ISSUE THREAD

**Issue by iasonkrom** [dask-contrib/dask-awkward#340]
```python
import dask_awkward as dak
from coffea.nanoevents import NanoAODSchema, NanoEventsFactory
from distributed import Client

fnames = {"../../coffea_dev/coffea/tests/samples/nano_dy.root": "Events"}

events = NanoEventsFactory.from_root(
    fnames,
    schemaclass=NanoAODSchema,
    permit_dask=True,
).events()

mask = dak.num(events.Electron.pt) >= 1

(events[mask]).compute(scheduler="threads")

(events[mask]).compute(scheduler="processes")

with Client() as client:
    (events[mask]).compute()
```
From the above snippet, only the first compute works. The other two fail with
```
TypeError: unhashable type: 'dict'

This error occurred while calling

    ak.to_packed(
        <Array [{PuppiMET: {...}, ...}, ..., {...}] type='20 * NanoEvents[P...'>
        highlevel = False
    )
```
This  happens in `awkward>=2.3.0` and is independent of `dask-awkward` or `uproot` version. However it is dependent on `coffea`'s nanoevents. I wasn't able to reproduce this if events are read with plain `uproot`.

I don't know which is the "correct" package to post the issue so I'm tagging @lgray and awkward people @jpivarski @agoose77.
If you'd like to move this issue, let me know.

I would also like to note that in my code (https://github.com/iasonkrom/egamma-tnp/blob/6e379ebb784869bf38f09f91f2b790aa91469b69/src/egamma_tnp/_tnpmodules.py#L37) where more things happen afterwards during compute, this fails only with `scheduler="processes"` and works with the distributed `Client`.

**Comment by agoose77** [comment]
@iasonkrom this is an Awkward bug, and I'm responsible! I'll make a bugfix to correct the oversight shortly :)
