### ISSUE TITLE
dak.ones_like yields spuriously correct touching?

### ISSUE THREAD

**Issue by lgray** [dask-contrib/dask-awkward#359]
```python3
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema
import dask_awkward as dak
import uproot

if __name__ == "__main__":

    events = uproot.dask({"https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root": "Events"}, open_files=False)

    print(dak.necessary_columns(dak.ones_like(events.Muon_pt)))
    print(dak.ones_like(events.Muon_pt).compute())

    events = NanoEventsFactory.from_root(
        {"https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root": "Events"},
        metadata={"dataset": "nano_dy"},
        schemaclass=NanoAODSchema,
        permit_dask=True,
    ).events()

    print(dak.necessary_columns(dak.ones_like(events.Muon.pt)))
    print(dak.ones_like(events.Muon.pt).compute())
```
Fails with `awkward.errors.FieldNotFoundError: no field 'pt' in record with 1 fields`.

The raw uproot case is working. This has been working in the past but I've lost track of what's supposed to work when.

**Comment by lgray** [comment]
Ah, this is yet another reproduction of #313 - what is the status of being able to fix that? It's critical to making a generally usable release of coffea, and is now causing tests to fail now that we're bringing all the tests back to regular rotation.

**Comment by lgray** [comment]
@agoose77 @douglasdavis

**Comment by douglasdavis** [comment]
with the latest awkward release and #327 that reproducer works without failure. It may have slipped past my radar that the upstream awkward changes that were necessary are now complete; is that the case, @agoose77?

**Comment by lgray** [comment]
Yes #327 fixes the coffea test as well (and torture tests remain unchanged).

**Comment by douglasdavis** [comment]
> (and torture tests remain unchanged).

as in they are good with #327?

**Comment by lgray** [comment]
Correct!
