### ISSUE TITLE
Calling compute on a mathematical operation

### ISSUE THREAD

**Issue by JaLuka98** [dask-contrib/dask-awkward#396]
Hi!

I was wondering if it is intended that `compute` fails when called on mathematical operations. @lgray suggested to report this "bug" here as he believes it should work. 

Example:
```
import awkward as ak
import dask
from coffea.nanoevents import NanoAODSchema, NanoEventsFactory

events = NanoEventsFactory.from_root(
    {"https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root": "Events"},
    schemaclass=NanoAODSchema,
    permit_dask=True,
).events()

n_from_e = ak.num(events.Electron, axis=0)
n_from_m = ak.num(events.Muon, axis=0)
ratio = n_from_e.compute() / n_from_m.compute() # works since 2023.10.1
num, den = dask.compute(n_from_e,n_from_m) # num/den can then be used
ele_over_mu = (n_from_e / n_from_m).compute() # does not work
```

To be precise, I am referring to the last line: `ele_over_mu = (n_eles / n_mus).compute()`, where the division takes place before computing the result.

Thank you!

Best,
Jan Lukas

edit: Sorry, some naming mismatch, now the example makes more sense.

**Comment by douglasdavis** [comment]
`TypeError: unsupported operand type(s) for /: 'Scalar' and 'Scalar'`

This is a missing implementation! The `Scalar` object in dask-awkward is very barebones since we typically work with arrays. `Scalar` needs `__truediv__` (and other operations from Python's `operator` library)

**Comment by JaLuka98** [comment]
Okay, thank you for the clarification!

**Comment by douglasdavis** [comment]
Alright this should be fixed!

`truediv` specifically will throw a warning about optimization failing when dividing two results of `dak.num` calls, due to https://github.com/scikit-hep/awkward/pull/2774. Other operations (`+`, `-`, `*`, etc.) are fine.
