### ISSUE TITLE
Calculating efficiencies by dividing dask-awkward collections

### ISSUE THREAD

**Issue by JaLuka98** [dask-contrib/dask-awkward#411]
Hello!

I am trying to calculate the efficiency of a selection, making use of Dask-awkward collections on the way. For this, a minimal working example can be found below.

```
import numpy as np
from coffea.nanoevents import NanoEventsFactory
import awkward as ak
import dask
import dask_awkward as dak

events = NanoEventsFactory.from_root(
    {"https://raw.githubusercontent.com/CoffeaTeam/coffea/master/tests/samples/nano_dy.root": "Events"},
    permit_dask=True,
).events()

sumWeights = dak.sum(events.genWeight)  # Calculate sumWeights before applying any selection to have proper preselection normalisation
events['genWeight'] = events.genWeight / dak.sum(events.genWeight, keepdims=True)

events = events[events.HLT.IsoMu24 == True]  # Apply a dummy selection

print(dak.sum(events.genWeight).compute()) # Just for testing purposes, returns 0.18198285

out = dak.zip({
    "lead_mu_pt": events.Muon[:,0].pt,
    "weight": events.genWeight,
})
skim = dak.to_parquet(out, "./my_wwe_skim", compute=False)
dask.compute(skim)

arr = ak.from_parquet('./my_wwe_skim')
print(ak.sum(arr.weight)) # Just for testing purposes, returns 0.18198285
```

The idea is to calculate `sumWeights` before applying the selection and then normalise the event weights by this value to have their sum equal the efficiency. However, the simplest option `events['genWeight'] = events.genWeight / dak.sum(events.genWeight)` fails with
```
dask_awkward.utils.DaskAwkwardNotImplemented: Use of Array with other Dask collections is currently unsupported.
If you would like this unsupported call to be supported by
dask-awkward please open an issue at:
https://github.com/dask-contrib/dask-awkward.
```

Instead, it appears necessary to add `keepdims=True`, which is quite obscure to me and it took some time and help from others to figure this out. Other beginners might run into the same issue. For your convenience,
```
print(dak.sum(events.genWeight, keepdims=True))  # dask.awkward<sum, npartitions=1>
print(dak.sum(events.genWeight))  # dask.awkward<sum, type=Scalar, dtype=float32>
``
so it seems that the operation `dask.awkward<genWeight, npartitions=1> / Scalar` (genWeight can be replaced by any field I think) is not supported. Is it possible to add support for this?

Thanks a lot!

Best,
Jan Lukas

**Comment by douglasdavis** [comment]
Hi @JaLuka98, what version of dask-awkward are you using? If I run 
```python
events['genWeight2'] = events.genWeight / dak.sum(events.genWeight)
```
I'm not seeing the error message

(using the Array collection with Scalar collections was recently added in [`2023.11.0`](https://github.com/dask-contrib/dask-awkward/releases/tag/2023.11.0)

**Comment by JaLuka98** [comment]
Hi @douglasdavis 

I was using `2023.10.2`. I was not aware that there is a newer version that supports operations with Arrays and Scalars. I upgraded the version in my conda environment and it works now even without `keepdims=True`. Thanks a lot!

Best,
Jan Lukas
