### ISSUE TITLE
bug: attrs do not survive compute()

### ISSUE THREAD

**Issue by lgray** [dask-contrib/dask-awkward#447]
```python3
import awkward
import dask_awkward

x = dask_awkward.from_awkward(awkward.Array([0]), 1)
x.attrs["test"] = "test"

print(x.attrs)

print(x.compute().attrs)
```

yields:
```
{'test': 'test'}
{}
```

**Comment by lgray** [comment]
It also happens that the serialized attrs are not available on the workers!

**Comment by martindurant** [comment]
I think in discussions we did want to distinguish between attrs of the dak array and the (ephemeral) attributes of the member ak arrays seen by the workers. I may be misremembering, but I didn't think syncing between them was intended.

**Comment by agoose77** [comment]
As @martindurant puts it, this is a natural consequence of the high-level dask-awkward arrays having metadata that is simply a "what would happen" view of the underlying operation. I'm not sure how we want to handle this — I think it is sensible that changing the attrs should be reflected in the result, but equally we probably need this to be a functional API that explicitly adds a mutation to the graph. As such, I'm thinking that `dask_awkward.Array.attrs`  (and `behavior`) should be read-only views, with a new `dask_awkward.with_attrs` function. I don't know that this would be a common function to use, so Awkward probably doesn't need to implement it too.
