### ISSUE TITLE
Calling `len` on a `dak.Array` can report the wrong length

### ISSUE THREAD

**Issue by jpivarski** [dask-contrib/dask-awkward#454]
Eager arrays:

```python
>>> import uproot, skhep_testdata
>>> a = uproot.open({skhep_testdata.data_path("uproot-HZZ.root"): "events"}).arrays()
>>> len(a)
2421
>>> b = a["Muon_Px", 0]
>>> len(b)
2
```

Lazy arrays:

```python
>>> a = uproot.dask({skhep_testdata.data_path("uproot-HZZ.root"): "events"})
>>> len(a)
2421
>>> b = a["Muon_Px", 0]
>>> len(b)
2421
```

With a slice, one can easily get into the situation in which the length is not known without reading data. `len` can't return an `unknown_length`, but it could be made to raise an exception. Even the length of the source array (`a` in the above) is not always known: setting the `files` to more than one file and `open_files=False` in [uproot.dask](https://uproot.readthedocs.io/en/latest/uproot._dask.dask.html) will create a source array whose length is not known.

Should `dak.Array.__len__` keep track of when it truly knows the length and when it doesn't? A second-best option would be for it to always raise a

```
ValueError: length of dak.Array is not known before computation
```

**Comment by martindurant** [comment]
We should be able to keep track of whether we know the length or not. We should ideally display it in the repr if we have the information.

In dask.dataframe, `len()` triggers compute, and that's a reasonable pattern to follow (we can put warnings in the documentation).

**Comment by jpivarski** [comment]
Good: it's a more narrow bug than I had thought. Using `a["Muon_Px"][0]` instead of `a["Muon_Px", 0]`:

```python
>>> import uproot, skhep_testdata
>>> a = uproot.dask({skhep_testdata.data_path("uproot-HZZ.root"): "events"})
>>> len(a)
2421
>>> b = a["Muon_Px"][0]
>>> len(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/mambaforge/lib/python3.10/site-packages/dask_awkward/lib/core.py", line 978, in __len__
    raise NotImplementedError(
NotImplementedError: Cannot determine length of collection with unknown partition sizes without executing the graph.
Use `dask_awkward.num(..., axis=0)` if you want a lazy Scalar of the length.
If you want to eagerly compute the partition sizes to have the ability to call `len` on the collection, use `.eager_compute_divisions()` on the collection.
```

returns an error, as expected. (I didn't expect `NotImplementedError` because I think this class implies that it's either an abstract superclass or is intended to be implemented later. I would have expected something like a `TypeError`, or maybe a `ValueError`.)

**Comment by douglasdavis** [comment]
Jim Pivarski ***@***.***> writes:

> Good: it's a more narrow bug than I had thought. Using `a["Muon_Px"][0]` instead of `a["Muon_Px", 0]`:
>
> ```python
>>>> import uproot, skhep_testdata
>>>> a = uproot.dask({skhep_testdata.data_path("uproot-HZZ.root"): "events"})
>>>> len(a)
> 2421
>>>> b = a["Muon_Px"][0]
>>>> len(b)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/jpivarski/mambaforge/lib/python3.10/site-packages/dask_awkward/lib/core.py", line 978, in __len__
>     raise NotImplementedError(
> NotImplementedError: Cannot determine length of collection with unknown partition sizes without executing the graph.
> Use `dask_awkward.num(..., axis=0)` if you want a lazy Scalar of the length.
> If you want to eagerly compute the partition sizes to have the ability to call `len` on the collection, use `.eager_compute_divisions()` on the collection.
> ```
>
> returns an error, as expected. (I didn't expect `NotImplementedError` because I think this class implies that it's either an abstract superclass or is intended to be implemented later. I would have expected something like a `TypeError`, or maybe a `ValueError`.)

I think TypeError is probably a good way to go (since the array's
divisions attribute type is tuple[None, ...] instead of tuple[int,
...]). I'll add that to the PR.
