### ISSUE TITLE
to_parquet mangling paths?

### ISSUE THREAD

**Issue by nsmith-** [dask-contrib/dask-awkward#458]
For a small test csv file:
```
thing1,thing2
1,2
3,4
3,4
...
```

I can read and write it to a remote filesystem with dask.dataframe:
```python
import dask.dataframe as dd

df = dd.read_csv("root://cmseos.fnal.gov//store/user/ncsmith/test.csv", blocksize="500b")
df.to_parquet("root://cmseos.fnal.gov//store/user/ncsmith/test")
```
and I can read it but _not_ write it with dask-awkward:
```python
import dask_awkward as dak

arr = dak.from_parquet("root://cmseos.fnal.gov//store/user/ncsmith/test")
arr.to_parquet("root://cmseos.fnal.gov//store/user/ncsmith/test2")
```
the last line raises the error:
```
File /opt/conda/lib/python3.10/site-packages/dask_awkward/lib/io/parquet.py:508, in _ToParquetFn.__call__(self, data, block_index)
    506     filename = f"{self.prefix}-{filename}"
    507 filename = f"{self.protocol}://{self.path}/{filename}"
--> 508 return ak.to_parquet(
    509     data, filename, **self.kwargs, storage_options=self.storage_options
    510 )

...

ValueError: Invalid hostid: ''

This error occurred while calling

    ak.to_parquet(
        <Array [{thing1: 1, thing2: 2, ...}, ...] type='140 * {thing1: ?int...'>
        'root:///store/user/ncsmith/test2/part0.parquet'
        list_to32 = False
        string_to32 = True
        bytestring_to32 = True
        emptyarray_to = None
        categorical_as_dictionary = False
        extensionarray = False
        count_nulls = True
        compression = 'zstd'
        compression_level = None
        row_group_size = 67108864
        data_page_size = None
        parquet_flavor = None
        parquet_version = '2.4'
        parquet_page_version = '1.0'
        parquet_metadata_statistics = True
        parquet_dictionary_encoding = False
        parquet_byte_stream_split = False
        parquet_coerce_timestamps = None
        parquet_old_int96_timestamps = None
        parquet_compliant_nested = False
        parquet_extra_options = None
        storage_options = None
    )
```
@martindurant

**Comment by nsmith-** [comment]
One thing I noticed is that dask.array uses `get_fs_token_paths` to parse the input path:
https://github.com/dask/dask/blob/82eaba0060939f8e38b649480301ac91c4835c75/dask/dataframe/io/parquet/utils.py#L73
while dask-awkward uses `url_to_fs`
 https://github.com/dask-contrib/dask-awkward/blob/main/src/dask_awkward/lib/io/parquet.py#L642

**Comment by douglasdavis** [comment]
Nicholas Smith ***@***.***> writes:

> One thing I noticed is that dask.array uses `get_fs_token_paths` to parse the input path:
> https://github.com/dask/dask/blob/82eaba0060939f8e38b649480301ac91c4835c75/dask/dataframe/io/parquet/utils.py#L73
> while dask-awkward uses `url_to_fs`
>  https://github.com/dask-contrib/dask-awkward/blob/main/src/dask_awkward/lib/io/parquet.py#L642

Can we use the filesystem object which has already been instantiated in
the dask-awkward code to get the cmseos.fnal.gov part of the full string
that needs to get passed to `ak.from_parquet`? Or maybe it'd be better
to just be able to pass that filesystem object directly to the
`ak.from_parquet` call?

**Comment by douglasdavis** [comment]
Can we use the filesystem object which has already been instantiated in the dask-awkward code to get the cmseos.fnal.gov part of the full string that needs to get passed to `ak.from_parquet`? Or maybe it'd be better to just be able to pass that filesystem object directly to the `ak.from_parquet` call?

**Comment by lgray** [comment]
```
>>> import fsspec
>>> f = fsspec.open("root://cmsdcadisk.fnal.gov//store/data/Run2023C/EGamma0/NANOAOD/PromptNanoAODv11p9_v1-v1/70000/")
>>> f.fs.hostid
'cmsdcadisk.fnal.gov:1094'
```

**Comment by nsmith-** [comment]
Don't use `hostid` because that is not always the same attribute on all FileSystem (s)
p.s. I wanted it called `host` but gave up. In some others it is.

**Comment by nsmith-** [comment]
I think what you actually want is `fs.unstrip_protocol(path)`. It will be fs-implementation-dependent, and here it is https://github.com/CoffeaTeam/fsspec-xrootd/blob/main/src/fsspec_xrootd/xrootd.py#L212

**Comment by nsmith-** [comment]
Or use `fs.open(path)` to create the file handle (this looks to be what the dask.dataframe does iiuc)

**Comment by lgray** [comment]
yep:
```
>>> f.fs.unstrip_protocol('/store/data/Run2023C/EGamma0/NANOAOD/PromptNanoAODv11p9_v1-v1/70000')
'root://cmsdcadisk.fnal.gov:1094//store/data/Run2023C/EGamma0/NANOAOD/PromptNanoAODv11p9_v1-v1/70000'

```
