### ISSUE TITLE
bug: optimized dask-awkward task graphs involving a histogram synchronize on histreduce-agg

### ISSUE THREAD

**Issue by lgray** [dask-contrib/dask-awkward#464]
reproducer:
```python3
import uproot

from distributed import Client
import awkward as ak
import dask

import hist.dask

if __name__ == "__main__":
    client = Client()

    events, report = uproot.dask(
        {"./Run2012B_SingleMu.root": {"object_path": "Events"}},
        steps_per_file=500,
        allow_read_errors_with_report = True,
    )

    thehist = (
        hist.dask.Hist.new
        .Reg(60, 0, 60, name="pt")
        .Double()
        .fill(ak.flatten(events.Muon_pt))
    )

    dask.compute(thehist, report)
```

causes the calculation of the `report` to wait for the complete, final, histogram to be calculated before finishing the calculation of `second` (the report).

Example of execution in progress:
<img width="1255" alt="image" src="https://github.com/dask-contrib/dask-awkward/assets/1068089/b1eeb2a8-7bd3-48d4-92d4-046b21b116c1">

However, if the un-optimized taskgraph is run then the report is calculated in parallel.

Example of un-optimized task graph executing:
<img width="1252" alt="image" src="https://github.com/dask-contrib/dask-awkward/assets/1068089/4c9e2608-2cf7-4c20-93da-87e17dfed811">

@nsmith- @douglasdavis @martindurant 

This is *rather* performance critical, and required some odd conditions to make happen.

**Comment by lgray** [comment]
This might belong on dask-histogram, given it's caused by that, but since it's an optimization problem it seems likely the issue has its roots here.

**Comment by douglasdavis** [comment]
Could be dask-histogram's fault. Maybe because the collections are different, the optimization is getting screwed up somehow (when simultaneously computing the report with a dak.Array collection then of course both the report and the "real" collection are the same).

**Comment by lgray** [comment]
Hmm I tried this with: `dask.compute(ak.sum(ak.count(events.Muon_pt, axis=1)), report)`

and that computes the report in parallel perfectly well, and the collections are different (since ak.sum results in a dak.Scalar)

I suppose that identifies dask-histogram as the culprit in some capacity, but not for the reason we think.

**Comment by douglasdavis** [comment]
If you run `dask.compute(ak.flatten(events.Muon_pt), report) do you get the same behavior (then it definitely wouldn't be dask-histogram's fault)?

**Comment by douglasdavis** [comment]
jinx :) ok good find

**Comment by douglasdavis** [comment]
if you run `hist_opt, hist_report = dask.optimize(hist, report)` do `hist` and `report` share the same `AwkwardInputLayer`? I'm wondering if a dask-histogram optimization fails to retain the shared dependency up the task graph

**Comment by lgray** [comment]
That looks fine:
```
>>> hist_opt, report_opt = dask.optimize(thehist, report)
>>> hist_opt.dask
HighLevelGraph with 3 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x16fc88850>
 0. second-72074915e20c3281151cf1bb492215c0
 1. hist-on-block-f23ae12aaf6f1170597fa1c4d1005733
 2. histreduce-agg-e2a6253ad5b732032144f6db72c62c1d

>>> report_opt.dask
HighLevelGraph with 3 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x16fc88850>
 0. second-72074915e20c3281151cf1bb492215c0
 1. hist-on-block-f23ae12aaf6f1170597fa1c4d1005733
 2. histreduce-agg-e2a6253ad5b732032144f6db72c62c1d
 ```

**Comment by lgray** [comment]
though I guess I need to dig into the subgraph callable to see the input layer.

**Comment by lgray** [comment]
Oh now *this* is interesting:
```
>>> hist_opt.dask.layers["second-72074915e20c3281151cf1bb492215c0"].dsk
{'from-uproot-e2e9651a23227a1eb50dcc813f489e30': (<uproot._dask._UprootRead object at 0x2a366d340>, '__dask_blockwise__0'), 'second-72074915e20c3281151cf1bb492215c0': (<dask_awkward.lib.core.ArgsKwargsPackedFunction object at 0x16fc56f10>, 'from-uproot-e2e9651a23227a1eb50dcc813f489e30')}
>>> hist_opt.dask.layers["hist-on-block-f23ae12aaf6f1170597fa1c4d1005733"].dsk
{'from-uproot-e2e9651a23227a1eb50dcc813f489e30': (<uproot._dask._UprootRead object at 0x16fe54340>, '__dask_blockwise__0'), 'first-55b4dcc09bab99a30bfc079ab3384086': (<dask_awkward.lib.core.ArgsKwargsPackedFunction object at 0x16fc88a00>, 'from-uproot-e2e9651a23227a1eb50dcc813f489e30'), 'Muon-pt-2518c2b661a8700c088b1b95e3391b83': (<dask_awkward.lib.core.ArgsKwargsPackedFunction object at 0x16fc56ac0>, 'first-55b4dcc09bab99a30bfc079ab3384086', 'Muon_pt'), 'flatten-a888f032d6154fb1ae6fc0969a5a4bd2': (<dask_awkward.lib.core.ArgsKwargsPackedFunction object at 0x16fc88490>, 'Muon-pt-2518c2b661a8700c088b1b95e3391b83'), 'hist-on-block-f23ae12aaf6f1170597fa1c4d1005733': (<function apply at 0x1179fe040>, <function _blocked_dak at 0x121705670>, ['flatten-a888f032d6154fb1ae6fc0969a5a4bd2', None, None], (<class 'dict'>, [['histref', ((Regular(60, 0, 60, name='pt'),), <class 'boost_histogram.storage.Double'>, None)]]))}
```

**Comment by lgray** [comment]
It's the same `from-uproot` task and key *but* it's two different `uproot._dask._UprootRead` objects!

**Comment by douglasdavis** [comment]
since they were simultaneously optimized they should have teh same `__dask_graph__` but should each represent a different `__dask_keys__`

**Comment by douglasdavis** [comment]
> It's the same `from-uproot` task and key _but_ it's two different `uproot._dask._UprootRead` objects!

huh that's definitely weird, I'm guessing in the non-dask-histogram case the `_UprootRead` objects are the same?

**Comment by lgray** [comment]
The keys appear to be the same as well:
```
>>> hist_opt.dask.layers["hist-on-block-f23ae12aaf6f1170597fa1c4d1005733"].dsk.keys()
dict_keys(['from-uproot-e2e9651a23227a1eb50dcc813f489e30', 'first-55b4dcc09bab99a30bfc079ab3384086', 'Muon-pt-2518c2b661a8700c088b1b95e3391b83', 'flatten-a888f032d6154fb1ae6fc0969a5a4bd2', 'hist-on-block-f23ae12aaf6f1170597fa1c4d1005733'])
>>> hist_opt.dask.layers["second-72074915e20c3281151cf1bb492215c0"].dsk.keys()
dict_keys(['from-uproot-e2e9651a23227a1eb50dcc813f489e30', 'second-72074915e20c3281151cf1bb492215c0'])
```

**Comment by lgray** [comment]
ahhh here is a clue:

```
>>> calc_opt, report_opt = dask.optimize(ak.sum(ak.count(events.Muon_pt, axis=1)), report)
>>> calc_opt.dask
HighLevelGraph with 4 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x16da29d60>
 0. from-uproot-e2e9651a23227a1eb50dcc813f489e30
 1. second-72074915e20c3281151cf1bb492215c0
 2. -chunk-reducer-non-positional-9985e160db9c7a79976003badb8758ae
 3. sum-finalize-dbab2bbe3080ffbc95d780ead003a05b

>>> calc_opt, report_opt = dask.optimize(ak.flatten(events.Muon_pt), report)
>>> calc_opt.dask
HighLevelGraph with 3 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x16da325b0>
 0. from-uproot-e2e9651a23227a1eb50dcc813f489e30
 1. second-72074915e20c3281151cf1bb492215c0
 2. flatten-2d1bc6826a71ff7dd4a43fd5fcb31554
 ```
 
 Notice that the uproot layer isn't getting optimized out!

**Comment by lgray** [comment]
so it *cannot* make a copy the uproot input layer.

**Comment by lgray** [comment]
So why is it causing overly aggressive optimizations in the dask-histogram case... I guess it's a different layer type, but they're all blockwise...

**Comment by douglasdavis** [comment]
Ah yes another good find! This "save the input layer from being optimized" behavior is ringing a bell. I'll dig some

**Comment by douglasdavis** [comment]
in `dask_awkward.lib.optimize.rewrite_layer_chains` there are checks specifically for `AwkwardBlockwiseLayer` instances, which dask-histogram is _not_ creating.

And the `rewrite_layer_chains` logic was updated in https://github.com/dask-contrib/dask-awkward/pull/37 to make sure we didn't over aggressively optimize a graph (an example of something getting over optimized would be hiding the input layer when it would be needed).

**Comment by lgray** [comment]
Ah so even though:
```
>>> thehist.dask
HighLevelGraph with 6 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x16ae19e80>
 0. from-uproot-2f30c71f0b6448b2aeb0c355ffb98eb0
 1. first-4fc665481129b59d92ffce17cd0ed628
 2. Muon-pt-2d148da672dfec38a62dbfda32c13d26
 3. flatten-3566faa6738738c5637711f4c1fbb381
 4. hist-on-block-8cfab2e4ef700570c6a380193a2ab42f
 5. histreduce-agg-1e50af080bd8321ef426e689e755214b
 
>>> thehist.dask.layers["hist-on-block-8cfab2e4ef700570c6a380193a2ab42f"]
AwkwardBlockwise<(('flatten-3566faa6738738c5637711f4c1fbb381', ('.0',)), (None, None), (None, None)) -> hist-on-block-8cfab2e4ef700570c6a380193a2ab42f>
>>> thehist.dask.layers["histreduce-agg-1e50af080bd8321ef426e689e755214b"]
DataFrameTreeReduction<name='histreduce-agg-1e50af080bd8321ef426e689e755214b', input_name=hist-on-block-8cfab2e4ef700570c6a380193a2ab42f, split_out=None>
```
The latter kills it?

**Comment by douglasdavis** [comment]
If you can maybe change those `isinstance(..., AwkwardBlockwiseLayer)` checks to `isinstance(..., Blockwise)` and see what happens

**Comment by douglasdavis** [comment]
Ah if the tree reduction layer is causing things to break then maybe dask-histogram may need to be using https://github.com/dask-contrib/dask-awkward/blob/main/src/dask_awkward/layers/layers.py#L333 instead of DataFrameTreeReductionLayer

**Comment by lgray** [comment]
Yeah that's just what I was thinking!

**Comment by lgray** [comment]
No, that can't be it! It's not checked for as a protected case in `rewrite_layer_chains`.

**Comment by lgray** [comment]
Huh - even if I completely comment out `rewrite_layer_chains` so it is never executed it does not change this behavior.

**Comment by douglasdavis** [comment]
Hmm maybe turn off the upstream blockwise optimization

https://github.com/dask-contrib/dask-histogram/blob/5289f10faac1328a3ca8aa970c33c5a6726fd988/src/dask_histogram/core.py#L421

and see what happens

**Comment by lgray** [comment]
something's definitely happening in `rewrite_layer_chains` still:
these are the resulting layers:
```
{'hist-on-block-617a99687c60189a6c026a5492bb0e88': AwkwardBlockwise<(('cab8b053ad8527278792ceed9902e280', ('.0',)),) -> hist-on-block-617a99687c60189a6c026a5492bb0e88>, 'histreduce-agg-92a70bdb7aa7f08c26ce9d81d3a31c0b': DataFrameTreeReduction<name='histreduce-agg-92a70bdb7aa7f08c26ce9d81d3a31c0b', input_name=hist-on-block-617a99687c60189a6c026a5492bb0e88, split_out=None>}
{'second-cca0b56f66a1d1557cd237d1a79f8b83': AwkwardBlockwise<(('86601cb3d371da6a2efb8de7b253d809', ('.0',)),) -> second-cca0b56f66a1d1557cd237d1a79f8b83>}
```

so `from-uproot` is getting scrubbed out in this pass.

**Comment by lgray** [comment]
wow, it's still doing it even if I remove `rewrite_layer_chains` and `optimize_blockwise` except only `second` gets the uproot layer merged in.

**Comment by lgray** [comment]
Ah! I think I found it.

What appears to be going on is when we have:
```python3
hist_opt, report_opt = dask.optimize(thehist, report)
```

both `dask_awkward.lib.optimize.all_optimizations` *and* `dask_histogram.core.optimize` are being run separately on each input somehow.

Since they're getting optimized separately, the report thinks its alone and gets optimized down to one layer with the uproot-read inside and and the histogram building gets its own copy since it's optimized seperately.

I made it print out when the function gets called.

```
>>> dask.optimize(thehist, report)[0].dask
dask-histogram optimize
dask-awkward all_optimizations
HighLevelGraph with 3 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x13ceae880>
 0. second-69cde23ad7d1ae445924d5121bd184c3
 1. hist-on-block-df383c2cbde2b003a6f616ab4f88dec4
 2. histreduce-agg-5b27bdcb198cdfa4f6ae2800cef9466a
 ```

**Comment by lgray** [comment]
Shouldn't it *only* be calling one of these on all of them?

**Comment by lgray** [comment]
This seems to answer that:
https://github.com/dask/dask/blob/main/dask/base.py#L418-L447

It *does* optimize each branch separately based on however this is doing groupings.

**Comment by lgray** [comment]
I have a fix!

**Comment by lgray** [comment]
Over in dask-histogram.

**Comment by douglasdavis** [comment]
> So that's definitely what is causing this behavior, the histogram optimization never knows about the report!

ah wow yeah I see it. another instance of mixing collection optimizations being a playing-with-fire activity. So the fix in dask-histogram just treats the optimization as a "I'm a dask-awkward collection" optimization (if dask-awkward has been imported as determined by dask.config)? That does seem like the safest route in a world where there are no dask-histogram specific optimizations :)

**Comment by lgray** [comment]
Yeah given the current setup it probably makes sense.

I guess in the future if there are dask-histogram specific optimizations we can monkey patch dask-awkward from dask-histogram and still share the same optimization function.

**Comment by lgray** [comment]
Huh I guess that also means we should *already* monkey patch dask.delayed and dask.array?

We already have dak / delayed mixed workflows in coffea. It may be skipping optimizations in certain topologies? Though I guess there's no specific optimizations we are missing in those cases?

Actually I guess there's not a big reason to not default to dask.array's optimize rather than even having one in dask-histogram for now?

**Comment by martindurant** [comment]
Optimization happens at bridges like to_array, which does pose the question of what happens when combining multiple arrays made in this way. When using arrays/delayed in a dak/dhist chain, it should be fine I think.

Starting to sound like we need a dak.compute whose sole job is to apply our own optimisations before passing on to dask.compute. There's your ugly patch.
