### ISSUE TITLE
full_like seems to hang with dask_awkward

### ISSUE THREAD

**Issue by jcatmore** [dask-contrib/dask-awkward#476]
Hello,

I've observed that if ```full_like``` is used to create an array with dask_awkward, the job hangs. According to the Dask monitor the computations are completed, but thereafter the job hangs. An identical set-up with the ```full_like``` arrays removed completes as normal, and if the job is run with plan Awkward Array (no Dask) it also seems to work as normal.

Is this problem known? 

I am using dask-awkward ```2023.8.1``` and uproot ```5.0.10```

I have put a reproducer (in the form of a notebook) in this repository in case someone wants to try to reproduce it:
https://github.com/jcatmore/DaskAwkwardTests  
Alongside the notebook I've put a screenshot of what the dask monitor shows at the point at which the job hangs.

Thanks and best wishes,

James (UiO/ATLAS)

**Comment by lgray** [comment]
These are very old versions of dask-awkward and uproot, does your problem still occur with a more recent software stack?

**Comment by jcatmore** [comment]
Hi @lgray ,

I updated to uproot ```5.2.2``` and dask-awkward ```2024.2.0```, and this indeed solved the problem. Thanks!

James

**Comment by agoose77** [comment]
@lgray thanks for following this up!
