### ISSUE TITLE
How to cite dask-awkward

### ISSUE THREAD

**Issue by Zethson** [dask-contrib/dask-awkward#495]
Hey,

thank you very much for your hard work! How would I cite dask-awkward?

Thanks!

**Comment by martindurant** [comment]
You may wish to note the acknowledgement section of the README: https://github.com/dask-contrib/dask-awkward?tab=readme-ov-file#acknowledgements and the awkward project in general. Dask also has guidance on citations: https://dask-local.readthedocs.io/en/latest/cite.html#citations

There is not, however, a citable entry for dask-awkward itself - a link to the repo or documentation I think would be fine for most uses.

**Comment by Zethson** [comment]
Thanks!
