### ISSUE TITLE
Implement `dak.backend` as an overload of `ak.backend`

### ISSUE THREAD

**Issue by jpivarski** [dask-contrib/dask-awkward#497]
The implementation would be really easy:

```python
# in dask-awkward

def backend(*arrays):
    ak_arrays = [x._meta if isinstance(x, dak.Array) else x for x in arrays]
    return ak.backend(*ak_arrays)
```

but it would fix scikit-hep/awkward#3077. See the discussion there, particularly the _end_ of https://github.com/scikit-hep/awkward/issues/3077#issuecomment-2049843773.

**Comment by martindurant** [comment]
Do you intend to make this a PR? I don't see any problem with it.

**Comment by jpivarski** [comment]
In which module should I put it?

**Comment by jpivarski** [comment]
utils.py doesn't have user-facing functions. The describe.py/reducers.py/structure.py is reminiscent of the way Awkward 1 organized its functions (same module names), before we switched to having one file per `ak.*` function, which I like much better, even if some of the files are really small.

In the describe.py/reducers.py/structure.py taxonomy, I guess `backend` would go into describe.py, so I'll put it there.

I'll open PR.

**Comment by agoose77** [comment]
I'm about to head out the door, but this would always return typetracer for meta arrays, which is probably not what we want.

**Comment by jpivarski** [comment]
In fact, I wrote the test as `assert dak.backend(daa) == "typetracer"`. Coffea code is using `ak.backend(something)` to determine if `something` is a typetracer-backed array. Right now, that's equivalent to being a dask-awkward array and they could have checked `isinstance(something, (dak.Array, dak.Record, dak.Scalar))` instead, but checking the backend may be preferable.
